version: 2
jobs:
  build:
    working_directory: ~/jekyll
    branches:
      only:
        - development
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run:
          name: Prepare
          command: 'bundle install'
      - run:
          name: Build
          command: 'bundle exec jekyll build'
      - run:
          name: Deploy
          command: 'scripts/deploy-site.sh'
