version: 2
jobs:
  build:
    working_directory: ~/jekyll
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run:
          name: Prepare
          command: 'bundle install'
      - run:
          name: Build
          command: 'bundle exec jekyll build'
